#if !canImport(ObjectiveC)
import XCTest

extension DocumentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DocumentTests = [
        ("testGraphQLStringWithObjectFieldsFragments", testGraphQLStringWithObjectFieldsFragments),
    ]
}

extension FieldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FieldTests = [
        ("testSerializeAlias", testSerializeAlias),
    ]
}

extension FoundationExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FoundationExtensionsTests = [
        ("testArgumentStringJsonEncodes", testArgumentStringJsonEncodes),
        ("testNSNullJsonEncodes", testNSNullJsonEncodes),
        ("testNSNumberJsonEncodes", testNSNumberJsonEncodes),
    ]
}

extension FragmentDefinitionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FragmentDefinitionTests = [
        ("testFragmentNamedOnIsNil", testFragmentNamedOnIsNil),
        ("testGraphQLStringWithDirectives", testGraphQLStringWithDirectives),
        ("testGraphQLStringWithFragments", testGraphQLStringWithFragments),
        ("testGraphQLStringWithObjectFields", testGraphQLStringWithObjectFields),
        ("testGraphQLStringWithScalarFields", testGraphQLStringWithScalarFields),
        ("testSelectionSetName", testSelectionSetName),
        ("testWithoutSelectionSetIsNil", testWithoutSelectionSetIsNil),
    ]
}

extension InlineFragmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InlineFragmentTests = [
        ("testInlineFragment", testInlineFragment),
        ("testObjectWithInlineFragment", testObjectWithInlineFragment),
        ("testSelectionSetName", testSelectionSetName),
    ]
}

extension InputValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InputValueTests = [
        ("testArrayInputValue", testArrayInputValue),
        ("testBoolInputValue", testBoolInputValue),
        ("testDictionaryInputValue", testDictionaryInputValue),
        ("testDoubleInputValue", testDoubleInputValue),
        ("testEmptyArrayInputValue", testEmptyArrayInputValue),
        ("testEmptyDictionaryInputValue", testEmptyDictionaryInputValue),
        ("testEnumInputValue", testEnumInputValue),
        ("testIDInputValue", testIDInputValue),
        ("testIntInputValue", testIntInputValue),
        ("testNonNullInputValue", testNonNullInputValue),
        ("testNSNullInputValue", testNSNullInputValue),
        ("testVariableInputValue", testVariableInputValue),
    ]
}

extension ObjectTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObjectTests = [
        ("testGraphQLStringWithAlias", testGraphQLStringWithAlias),
        ("testGraphQLStringWithObjectFields", testGraphQLStringWithObjectFields),
        ("testGraphQLStringWithoutAlias", testGraphQLStringWithoutAlias),
        ("testGraphQLStringWithScalarFields", testGraphQLStringWithScalarFields),
        ("testThrowsIfNoFieldsOrFragments", testThrowsIfNoFieldsOrFragments),
    ]
}

extension OperationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OperationTests = [
        ("testDirectives", testDirectives),
        ("testInitializersOnSelectionTypeArray", testInitializersOnSelectionTypeArray),
        ("testMutationForms", testMutationForms),
        ("testQueryForms", testQueryForms),
        ("testSelectionSet", testSelectionSet),
        ("testSubscriptionForms", testSubscriptionForms),
        ("testVariableDefinitions", testVariableDefinitions),
        ("testVariableVariablesWithDefaultValuesFail", testVariableVariablesWithDefaultValuesFail),
    ]
}

extension OrderedDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedDictionaryTests = [
        ("testsMaintainsOrder", testsMaintainsOrder),
    ]
}

extension ScalarTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScalarTests = [
        ("testGraphQLStringAsLiteral", testGraphQLStringAsLiteral),
        ("testGraphQLStringWithAlias", testGraphQLStringWithAlias),
        ("testGraphQLStringWithoutAlias", testGraphQLStringWithoutAlias),
    ]
}

extension SelectionSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SelectionSetTests = [
        ("testGraphQLString", testGraphQLString),
        ("testKey", testKey),
        ("testKind", testKind),
        ("testMergingFragmentSpreads", testMergingFragmentSpreads),
        ("testMergingScalars", testMergingScalars),
        ("testMergingSelections", testMergingSelections),
        ("testMergingSelectionsOfSameKeyButDifferentTypeFails", testMergingSelectionsOfSameKeyButDifferentTypeFails),
        ("testSelectionSetName", testSelectionSetName),
        ("testSerializedSelections", testSerializedSelections),
    ]
}

extension VariableTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VariableTest = [
        ("testVariableInputValue", testVariableInputValue),
        ("testVariableTypeThrows", testVariableTypeThrows),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DocumentTests.__allTests__DocumentTests),
        testCase(FieldTests.__allTests__FieldTests),
        testCase(FoundationExtensionsTests.__allTests__FoundationExtensionsTests),
        testCase(FragmentDefinitionTests.__allTests__FragmentDefinitionTests),
        testCase(InlineFragmentTests.__allTests__InlineFragmentTests),
        testCase(InputValueTests.__allTests__InputValueTests),
        testCase(ObjectTests.__allTests__ObjectTests),
        testCase(OperationTests.__allTests__OperationTests),
        testCase(OrderedDictionaryTests.__allTests__OrderedDictionaryTests),
        testCase(ScalarTests.__allTests__ScalarTests),
        testCase(SelectionSetTests.__allTests__SelectionSetTests),
        testCase(VariableTest.__allTests__VariableTest),
    ]
}
#endif
